version: "3.7"
services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python producer.py
    volumes:
      - ./producer.py:/app/producer.py
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  consumer_alpha:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    volumes:
      - ./consumer.py:/app/consumer.py
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  consumer_beta:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./consumer.py:/app/consumer.py
    restart: unless-stopped
    command: python consumer.py
    depends_on:
      - rabbitmq
    networks:
      - rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"

    networks:
      - rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  rabbit:
    driver: bridge
